spring:
  datasource:
    url: jdbc:sqlite:./data/request-assistant.db
    driver-class-name: org.sqlite.JDBC

  flyway:
    enabled: true

log:
  path: /logs
  level: INFO

mail.folder:
  root: Pa.Voci@almaviva.it
  in_arrivo: RichiesteAbilitazioni
  in_lavorazione: in_lavorazione
  evase: evase
