spring:
  datasource:
    url: jdbc:sqlite:../request-assistant-application/data/request-assistant.db
    driver-class-name: org.sqlite.JDBC
  flyway:
    enabled: true
  

mail.folder:
  root: Pa.Voci@almaviva.it
  in_arrivo: RichiesteAbilitazioni
  in_lavorazione: in_lavorazione
  evase: evase
  scartate: scartate

log:
  path: /logs
  level: DEBUG

ai:
  api:
    #key: ${AI_API_KEY}
    model: qwen3-8b-request-assistant-v4.2
    base-url: http://192.168.1.9:11434

email-address:
  focal-point: 'monica.pensotti@bper.it; ivan.dellepulle@bper.it; ian.daprada@bper.it'
  operatore: 'pa.voci@almaviva.it'